language: ruby
sudo: false
before_install:
  - gem install bundler

matrix:
  include:
    - rvm: 2.4.1
      script: bundle exec rake rubocop # ONLY lint once, first
    - rvm: 2.1
    - rvm: 2.2.7
    - rvm: 2.3.4
    - rvm: 2.4.1
    - rvm: jruby-1.7.27
    - rvm: jruby-9.1.14.0

env:
  global:
    - JRUBY_OPTS="--debug"
