language: ruby
sudo: false
before_install:
  - gem update --system
  - gem install bundler

matrix:
  include:
    - rvm: 2.4.0
      script: bundle exec rake rubocop # ONLY lint once, first
    - rvm: 2.1
    - rvm: 2.2
    - rvm: 2.3.3
    - rvm: 2.4.0
    - rvm: jruby-1.7.26
      env:
        - JRUBY_OPTS="--debug"
    - rvm: jruby-9.1.8.0
      env:
        - JRUBY_OPTS="--debug"
