language: ruby
sudo: false
before_install:
  - gem update --system
  - gem install bundler

matrix:
  include:
    - rvm: 2.4.1
      script: bundle exec rake rubocop # ONLY lint once, first
    - rvm: 2.1
    - rvm: 2.2.7
    - rvm: 2.3.4
    - rvm: 2.4.1
    - rvm: jruby-1.7.26
      env:
        - JRUBY_OPTS="--debug"
    - rvm: jruby-9.1.8.0
      env:
        - JRUBY_OPTS="--debug"
